apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: dev
data:
  CONFIG_SERVER_URL: "http://config-service:8888"
  FRONTEND_URL: "http://public-app:80"
  AUTH_SERVER_URL: "http://auth-server:9000"
  USER_MANAGEMENT_SERVICE_URL: "http://user-management-service:8081"
  RENTAL_AGREEMENT_URL: "http://rental-service:8083"
  PROPERTY_MICROSERVICE_URL: "http://property-service:8084"
  NOTIFICATION_MICROSERVICE_URL: "http://notification-service:8085"